sudo: false
language: python
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - gcc-5
    - php5-cli
    - php5-dev
    - python-dev
    - python-pip
    - ruby-dev
    - libdbus-glib-1-dev
    - libbluetooth-dev

cache:
  directories:
  - $HOME/.gradle
  - js/node_modules

env:
  global:
    - CXX=g++-5
    - GCC_COMPILER=yes
    - MCPP_HOME=${TRAVIS_BUILD_DIR}/mcpp
    - OPTIMIZE=yes
    - LMDB_REVISION=0.9.16
    - LMDB_BUILD_DIR=${TRAVIS_BUILD_DIR}/lmdb-LMDB_${LMDB_REVISION}
    - LMDB_HOME=${TRAVIS_BUILD_DIR}/lmdb
  matrix:
    - WORK_DIR=${TRAVIS_BUILD_DIR}/cpp CPP11_MAPPING=yes
    - WORK_DIR=${TRAVIS_BUILD_DIR}

python:
- "2.7"

before_install:
- git clone https://github.com/zeroc-ice/mcpp.git mcpp
- wget https://github.com/LMDB/lmdb/archive/LMDB_${LMDB_REVISION}.tar.gz
- tar xvf LMDB_${LMDB_REVISION}.tar.gz

install:
- make -C ${MCPP_HOME} -j3
- mkdir -p ${LMDB_HOME}/bin
- mkdir -p ${LMDB_HOME}/lib
- mkdir -p ${LMDB_HOME}/include
- mkdir -p ${LMDB_HOME}/man/man1
- CPPFLAGS=-fPIC make -C ${LMDB_BUILD_DIR}/libraries/liblmdb install prefix=${LMDB_HOME}
- rm -f ${LMDB_HOME}/lib/liblmdb.so
- pip install passlib
- make -C ${WORK_DIR} -j3

script:
- cd ${WORK_DIR}
- python allTests.py --debug --env --protocol=ssl

notifications:
  email: travis-ci@zeroc.com
  slack:
    secure: TywLzzH1Hx3Pb5I4s4wxbEZ9nOAPkamZDqHBOkpLSNSRa2iSk6n5GcQi5bnw0Ct59oTEytO/8fNP6mYwf5G2rrXGWpcdgSdyLMcUk6ASeO7ANv7xLKhVWbbOoVuZxFJvIG5mTYpCa3R58EtchQErzdyf3rRMN3rq/ZBmocFMcRY=
